# Generated by Django 4.1.7 on 2023-03-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='weeks_number',
            field=models.IntegerField(default=14),
        ),
    ]
